# Generated by Django 5.2.1 on 2025-05-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the department, centre or school.', unique=True, verbose_name='Department')),
                ('faculty', models.CharField(choices=[('Faculty of Engineering', 'Faculty of Engineering'), ('Faculty of Medicine', 'Faculty of Medicine'), ('Faculty of Natural Sciences', 'Faculty of Natural Sciences'), ('Imperial Business School', 'Imperial Business School'), ('Other', 'Other')], help_text='Faculty the department belongs to.', verbose_name='Faculty')),
            ],
        ),
    ]
