# Generated by Django 5.2.1 on 2025-05-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_department_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(help_text='Code for the activity to use during charging.', unique=True, verbose_name='Code')),
                ('description', models.CharField(help_text='Description of the code.', unique=True, verbose_name='Description')),
                ('notes', models.TextField(help_text='Longer explanation about when to use the code.', verbose_name='Notes')),
            ],
        ),
    ]
