# Generated by Django 5.2.1 on 2025-05-13 15:01

from django.db import migrations

from .. import utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_activitycode'),
    ]

    operations = [
        migrations.RunPython(
            code=utils.create_activities,  # type: ignore [arg-type]
            reverse_code=utils.destroy_activities  # type: ignore [arg-type]
            ),
    ]
