# Generated by Django 5.2.1 on 2025-05-22 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], help_text="'Internal' refers to projects from within ICT or community projects. If not 'Internal', all fields are mandatory.", verbose_name='Source')),
                ('funding_body', models.CharField(blank=True, help_text='The organisation or department providing the funding.', null=True, verbose_name='Funding body')),
                ('project_code', models.CharField(blank=True, help_text='The funding code designated to the project.', null=True, verbose_name='Project code')),
                ('expiry_date', models.DateField(blank=True, help_text='Account expiry date, meaning the latest that charges can be made to the account.', null=True, verbose_name='Expiry date')),
                ('budget', models.DecimalField(decimal_places=2, help_text='The total budget for the funding.', max_digits=6, verbose_name='Budget')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=389.0, help_text='The current daily rate, which defaults to 389.00.', max_digits=6, verbose_name='Daily rate')),
                ('activity_code', models.ForeignKey(blank=True, help_text='The activity code to use for charging.', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.activitycode')),
                ('project', models.ForeignKey(help_text='The project that the funding relates to.', on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
    ]
