# Generated by Django 5.2.1 on 2025-05-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_funding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funding',
            options={'verbose_name_plural': 'funding'},
        ),
        migrations.AlterField(
            model_name='funding',
            name='budget',
            field=models.DecimalField(decimal_places=2, help_text='The total budget for the funding.', max_digits=12, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=389.0, help_text='The current daily rate, which defaults to 389.00.', max_digits=12, verbose_name='Daily rate'),
        ),
    ]
