# Generated by Django 5.2.1 on 2025-05-28 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_funding_options_alter_funding_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0.7, help_text='Capacity fraction of 1 FTE devoted to project work.', max_digits=2, verbose_name='Capacity')),
                ('start_date', models.DateField(help_text='The date from when this capacity applies.', verbose_name='Start date')),
                ('user', models.ForeignKey(help_text='The team member this capacity relates to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'capacities',
            },
        ),
    ]
