# Generated by Django 5.2.1 on 2025-05-28 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.7, help_text='Capacity fraction of 1 FTE devoted to project work.', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Capacity'),
        ),
    ]
