# Generated by Django 5.2.1 on 2025-06-03 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_capacity_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='budget',
            field=models.DecimalField(decimal_places=2, help_text='The total budget for the funding.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=389.0, help_text='The current daily rate, which defaults to 389.00.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Daily rate'),
        ),
    ]
