# Generated by Django 5.2.1 on 2025-06-02 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_capacity_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='project',
            field=models.ForeignKey(help_text='The project that the funding relates to.', on_delete=django.db.models.deletion.CASCADE, related_name='funding_source', to='main.project'),
        ),
    ]
