# Generated by Django 5.2.2 on 2025-06-10 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_funding_budget_alter_funding_daily_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='The date and time when the work started.', verbose_name='Start time')),
                ('end_time', models.DateTimeField(help_text='The date and time when the work ended.', verbose_name='End time')),
                ('project', models.ForeignKey(help_text='The project this time entry relates to.', on_delete=django.db.models.deletion.CASCADE, to='main.project')),
                ('user', models.ForeignKey(help_text='The team member this time entry relates to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
