# Generated by Django 5.2.2 on 2025-06-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='clockify_id',
            field=models.CharField(blank=True, help_text='The ID of the project in Clockify, if applicable.', verbose_name='Clockify ID'),
        ),
    ]
