# Generated by Django 5.2.3 on 2025-06-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_project_clockify_id'),
        ('main', '0013_project_notifications_effort_and_more'),
    ]

    operations = [
    ]
