# Generated by Django 5.2.3 on 2025-06-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_merge_20250620_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='notifications_effort',
            field=models.JSONField(blank=True, default=dict, help_text='Summarises the notifications sent when an effort threshold is crossed and the corresponding dates.', verbose_name='Summary of effort left notifications'),
        ),
        migrations.AlterField(
            model_name='project',
            name='notifications_weeks',
            field=models.JSONField(blank=True, default=dict, help_text='Summarises the notifications sent when the weeks threshold is crossed and the corresponding dates.', verbose_name='Summary of weeks left notifications'),
        ),
    ]
