# Generated by Django 5.2.3 on 2025-06-24 09:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_project_notifications_effort_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount to be charged to the funding source.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount')),
                ('date', models.DateField(help_text='The date the charges related to (the month previous).', verbose_name='Charge date')),
                ('custom_description', models.CharField(blank=True, help_text='Custom line description for manual charges.', null=True, verbose_name='Custom description')),
                ('funding', models.ForeignKey(help_text='The funding source to be used for the charge.', on_delete=django.db.models.deletion.CASCADE, to='main.funding')),
                ('project', models.ForeignKey(help_text='The project the monthly charge relates to.', on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
    ]
