# Generated by Django 5.2.3 on 2025-06-25 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_monthlycharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='monthly_charge',
            field=models.ForeignKey(blank=True, help_text='The relevant monthly charge for this time entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.monthlycharge'),
        ),
    ]
