# Generated by Django 5.2.3 on 2025-07-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_timeentry_monthly_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funding',
            name='project_code',
        ),
        migrations.AddField(
            model_name='funding',
            name='activity',
            field=models.CharField(blank=True, help_text='The activity code designated to the project, 6 alphanumericcharacters starting with P, F or G.', null=True, verbose_name='activity'),
        ),
        migrations.AddField(
            model_name='funding',
            name='cost_centre',
            field=models.CharField(blank=True, help_text='The cost centre for the project.', null=True, verbose_name='Cost centre'),
        ),
    ]
