# Generated by Django 5.2.3 on 2025-07-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_funding_project_code_funding_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='monthly_charge',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='monthly_charge',
            field=models.ManyToManyField(blank=True, help_text='The relevant monthly charge for this time entry.', to='main.monthlycharge'),
        ),
    ]
