# Generated by Django 5.2.3 on 2025-07-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_funding_project_code_funding_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='clockify_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
