# Generated by Django 5.2.3 on 2025-07-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_timeentry_monthly_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='clockify_id',
            field=models.CharField(blank=True, help_text='The ID of the time entry in Clockify, if applicable.', verbose_name='Clockify ID'),
        ),
    ]
