# Generated by Django 5.2.4 on 2025-07-28 14:10

from django.db import migrations

from .. import utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_add_clockify_id_to_timeentry'),
    ]

    operations = [
        migrations.RunPython(
            code=utils.create_HoRSE_group,
            reverse_code=utils.destroy_HoRSE_group,
        ),
    ]
