# Generated by Django 5.2.6 on 2025-09-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_horse_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='activity',
            field=models.CharField(blank=True, help_text='The activity code designated to the project, 6 alphanumeric characters starting with P, F, G or I.', null=True, verbose_name='activity'),
        ),
    ]
