# Generated by Django 5.2.6 on 2025-09-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_funding_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycharge',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Confirmed', 'Confirmed')], default='Draft', help_text="The status of the monthly charge ('Draft' or 'Confirmed'). Confirmed monthly charges are not deleted.", max_length=20, verbose_name='Status'),
        ),
    ]
