# Generated by Django 5.2.6 on 2025-09-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_monthlycharge_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Tentative', 'Tentative'), ('Confirmed', 'Confirmed'), ('Active', 'Active'), ('Finished', 'Finished'), ('Not done', 'Not done')], default='Tentative', help_text="Status of the project. Unless the status is 'Tentative' or 'Not done', most other fields are mandatory.", verbose_name='Status'),
        ),
    ]
