# Generated by Django 5.2.6 on 2025-10-23 12:57

from django.db import migrations
from .. import utils

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_project_status'),
    ]

    operations = [
        migrations.RunPython(
            code=utils.create_RSE_group,
            reverse_code=utils.destroy_RSE_group,
        ),

    ]
