# Generated by Django 5.2.8 on 2025-11-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='The full-time-equivalent value over the specified period.', verbose_name='FTE value')),
                ('start_date', models.DateField(help_text='The date when the FTE begins.', verbose_name='Start date')),
                ('end_date', models.DateField(help_text='The date when the FTE ends.', verbose_name='End date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phases', to='main.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
