# Generated by Django 6.1 on 2026-08-25 07:07

from django.db import migrations

from .. import utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_projectphase'),
    ]

    operations = [
        migrations.RunPython(
            code=utils.create_RSETeam_group,
            reverse_code=utils.destroy_RSETeam_group,
        ),
    ]
