# Generated by Django 6.1 on 2026-09-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_add_RSEteam_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Tentative', 'Tentative'), ('Confirmed', 'Confirmed'), ('Active', 'Active'), ('Finished', 'Finished'), ('Not done', 'Not done'), ('Maintenance', 'Maintenance')], default='Tentative', help_text="Status of the project. Unless the status is 'Tentative' or 'Not done', most other fields are mandatory.", verbose_name='Status'),
        ),
    ]
