# Generated by Django 6.1.1 on 2026-09-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='is_maintenance',
            field=models.BooleanField(default=False, help_text='Indicates if this phase is the maintenance phase of the project.', verbose_name='Is maintenance phase'),
        ),
    ]
