# Generated by Django 6.1.1 on 2026-09-18 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_dailyrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='main.project'),
        ),
    ]
