# Generated by Django 6.1.1 on 2026-09-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_projectphase_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='kimai_id',
            field=models.IntegerField(blank=True, default=-1, help_text='The ID of the project in Kimai, if applicable.', verbose_name='Kimai ID'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='kimai_id',
            field=models.IntegerField(blank=True, default=-1, help_text='The ID of the time entry in Clockify, if applicable.', verbose_name='Kimai ID'),
        ),
    ]
