# Generated by Django 6.1.1 on 2026-10-08 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_kiami_id_project_time_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='The full-time-equivalent value over the specified period.', verbose_name='FTE value')),
                ('start_date', models.DateField(help_text='The date when the FTE begins.', verbose_name='Start date')),
                ('end_date', models.DateField(help_text='The date when the FTE ends.', verbose_name='End date')),
                ('priority', models.IntegerField(help_text='Priority of the Capacity')),
                ('user', models.ForeignKey(help_text='User this capacity relates to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Project Capacities',
                'unique_together': {('priority', 'user')},
            },
        ),
    ]
